apiVersion: v1
kind: Service
metadata:
  name: multi-arch-app-service
  namespace: multi-arch-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - port: 80
      targetPort: 5080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: multi-arch-app